# Generated by Django 4.0.3 on 2022-04-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_phone_alter_address_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(0, '未激活'), (1, '已激活')], default=1, verbose_name='激活状态'),
        ),
    ]
