# Generated by Django 4.0.3 on 2022-04-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(0, '未激活'), (1, '已激活')], default=0, verbose_name='激活状态'),
        ),
    ]
