# Generated by Django 4.0.3 on 2022-04-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_alter_commoditytype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoditytype',
            options={},
        ),
        migrations.AlterModelTable(
            name='commoditytype',
            table=None,
        ),
    ]
