# Generated by Django 4.0.3 on 2022-04-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_alter_commoditytype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commoditytype',
            options={'verbose_name': '商品种类', 'verbose_name_plural': '商品种类'},
        ),
    ]
