# Generated by Django 4.0.3 on 2022-04-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_alter_commoditytype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commdityimage',
            options={'verbose_name': '商品图片', 'verbose_name_plural': '商品图片'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': '商品名', 'verbose_name_plural': '商品名'},
        ),
        migrations.AlterModelOptions(
            name='commoditysku',
            options={'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
        migrations.AlterModelOptions(
            name='indexcommditybanner',
            options={'verbose_name': '首页轮播商品表', 'verbose_name_plural': '首页轮播商品表'},
        ),
        migrations.AlterModelOptions(
            name='indexpromotioinbanner',
            options={'verbose_name': '首页促销活动类型表', 'verbose_name_plural': '首页促销活动类型表'},
        ),
        migrations.AlterModelOptions(
            name='indextypecommditybanner',
            options={'verbose_name': '首页分类商品展示表', 'verbose_name_plural': '首页分类商品展示表'},
        ),
        migrations.AlterModelTable(
            name='commdityimage',
            table='df_Commodity_Image',
        ),
        migrations.AlterModelTable(
            name='commodity',
            table='df_Commodity',
        ),
        migrations.AlterModelTable(
            name='commoditysku',
            table='df_Commodity_SKU',
        ),
        migrations.AlterModelTable(
            name='indexcommditybanner',
            table='df_Index_Commodity_Banner',
        ),
        migrations.AlterModelTable(
            name='indexpromotioinbanner',
            table='df_Index_Promotionin_Banner',
        ),
        migrations.AlterModelTable(
            name='indextypecommditybanner',
            table='df_Index_Type_Commodity_Banner',
        ),
    ]
