# Generated by Django 4.0.3 on 2022-04-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_alter_commodity_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='detail',
            field=models.TextField(blank=True, verbose_name='商品详情'),
        ),
    ]
