# Generated by Django 4.0.3 on 2022-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0007_alter_commodity_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commdityimage',
            name='image',
            field=models.ImageField(upload_to='apps/commodity/static/img/img', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='commoditysku',
            name='image',
            field=models.ImageField(upload_to='apps/commodity/static/img/SKU', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='commoditytype',
            name='image',
            field=models.ImageField(upload_to='apps/commodity/static/img/type', verbose_name='展示图'),
        ),
        migrations.AlterField(
            model_name='indexcommditybanner',
            name='image',
            field=models.ImageField(upload_to='apps/commodity/static/img/banner', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='indexpromotioinbanner',
            name='image',
            field=models.ImageField(upload_to='apps/commodity/static/img/Promotionin', verbose_name='活动图片'),
        ),
    ]
