# Generated by Django 4.0.3 on 2022-04-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_times', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标签')),
                ('count', models.IntegerField(default=1, verbose_name='商品数目')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('comment', models.CharField(max_length=246, verbose_name='评论')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('create_times', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标签')),
                ('order_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '微信'), (2, '支付宝'), (3, '云闪付'), (4, '银联')], default=1, verbose_name='支付方式')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品金额')),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '代发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状况')),
                ('trade_no', models.CharField(max_length=128, verbose_name='订单编号')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
