# Generated by Django 4.0.3 on 2022-04-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordercommodity_options_alter_orderinfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.CharField(auto_created=True, max_length=128, primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
    ]
