# Generated by Django 4.0.3 on 2022-04-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderinfo_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='订单ID'),
        ),
    ]
