# Generated by Django 4.0.3 on 2022-04-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderinfo_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='transit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='运费'),
        ),
    ]
